spring:
  application:
    #注:SpringCloud中使用负载均衡和Gateway网关时，都要求应用名称中不能出现下划线，因此应用名称我们用中划线“-”
    name: service-user
  cloud:
    nacos:
      config:
        server-addr: 192.168.247.129:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:db-common.yaml
      - nacos:nacos-discovery.yaml
# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ticking.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.alibaba.cloud.nacos: debug

debug: true
