spring:
  application:
    #注:SpringCloud中使用负载均衡和Gateway网关时，都要求应用名称中不能出现下划线，因此应用名称我们用中划线“-”
    name: service-order
  cloud:
    nacos:
      config:
        server-addr: 192.168.247.129:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:db-common.yaml
      - nacos:nacos-discovery.yaml
    stream:
      rocketmq:
        binder:
          name-server: 192.168.247.129:9876  # 根据实际情况修改RocketMQ NameServer地址
      bindings:
        # 定义输入输出通道
        output:
          destination: order-topic
          content-type: application/json
        input:
          destination: order-topic
          group: order-group
          content-type: application/json
  data:
    redis:
      host: 192.168.247.129
      port: 6379
      password: 123456
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 3000ms
# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ticking.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.alibaba.cloud.nacos: debug

debug: true
