spring:
  application:
    #注:SpringCloud中使用负载均衡和Gateway网关时，都要求应用名称中不能出现下划线，因此应用名称我们用中划线“-”
    name: gateway
  cloud:
    nacos:
      config:
        server-addr: 192.168.247.129:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:db-common.yaml
  main:
    web-application-type: reactive  # 添加这行配置
logging:
  level:
    com.alibaba.cloud.nacos: debug

